name: VPS-Deploy

on:
    push:
      branches: [deploy-docker]
jobs:

    deploy:
        runs-on: ubuntu-latest
        timeout-minutes: 80
        steps:
            - name: Deploy to VPS
              uses: appleboy/ssh-action@master
              with:
                  command_timeout: 200m
                  host: ${{ secrets.VPS_SSH_HOST }}
                  username: ${{ secrets.VPS_SSH_USERNAME }}
                  key: ${{ secrets.VPS_SSH_SECRET }}
                  port: ${{ secrets.VPS_SSH_PORT }}
                  passphrase: ${{ secrets.SSH_PASSPHRASE }}
                  script: |
                      cd ${{ secrets.PROJECT_PATH }}
                      git pull origin deploy-docker
                      docker-compose down
                      docker-compose build 
                      docker-compose up -d
                      echo "Deleting old image(s)..."
                      docker image prune -a -f
